#!/usr/bin/env bash
# Generate a Factory Assistant update-channel document (stable/beta/dev.json).
#
# Derives the registry and OTA URL from branding/identity.env (the single
# source of truth — AGENTS.md), takes the per-component versions as flags, and
# emits a channel document matching version-service/schema/channel.schema.json.
# When a validator is available (check-jsonschema, or python3 + jsonschema) the
# output is validated before it is written.
#
# This is the mechanism for producing the document the Supervisor polls
# (docs/ARCHITECTURE.md §7). The registry/OTA/channel URLs are now settled
# (org=esaueng; channel on the esaueng/FactoryAssistant GitHub Pages site;
# OTA via that repo's GitHub Releases). Still validate the result against the
# pinned Supervisor's updater before publishing, and never mix FA and upstream
# artifact URLs (version-service/README.md).
#
# Usage:
#   scripts/../version-service/generate-channel.sh \
#       --channel stable --supervisor 2026.05.0 --core 2026.5.0 \
#       --os-board generic-x86-64 --os-version 17.3 [--out stable.json]
#
#   Plugin versions (--dns/--audio/--cli/--multicast/--observer) default to the
#   supervisor version. With no --out the document is printed to stdout.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=../branding/identity.env
source "$ROOT/branding/identity.env"

channel="stable"
supervisor=""
core=""
os_board=""
os_version=""
dns="" audio="" cli="" multicast="" observer=""
out=""

die() { echo "ERROR: $*" >&2; exit 2; }

while [ $# -gt 0 ]; do
    case "$1" in
        --channel)    channel="$2"; shift 2;;
        --supervisor) supervisor="$2"; shift 2;;
        --core)       core="$2"; shift 2;;
        --os-board)   os_board="$2"; shift 2;;
        --os-version) os_version="$2"; shift 2;;
        --dns)        dns="$2"; shift 2;;
        --audio)      audio="$2"; shift 2;;
        --cli)        cli="$2"; shift 2;;
        --multicast)  multicast="$2"; shift 2;;
        --observer)   observer="$2"; shift 2;;
        --out)        out="$2"; shift 2;;
        -h|--help)    sed -n '2,30p' "${BASH_SOURCE[0]}"; exit 0;;
        *)            die "unknown argument: $1";;
    esac
done

[ -n "$supervisor" ]  || die "--supervisor is required"
[ -n "$core" ]        || die "--core is required"
[ -n "$os_board" ]    || die "--os-board is required"
[ -n "$os_version" ] || die "--os-version is required"
command -v jq >/dev/null 2>&1 || die "jq is required"

# Plugins track the supervisor version unless overridden.
dns="${dns:-$supervisor}"
audio="${audio:-$supervisor}"
cli="${cli:-$supervisor}"
multicast="${multicast:-$supervisor}"
observer="${observer:-$supervisor}"

doc="$(jq -n \
    --arg comment "Generated by version-service/generate-channel.sh from branding/identity.env. Validate against the pinned Supervisor before publishing (version-service/README.md). Publish to the esaueng/FactoryAssistant GitHub Pages site; OTA bundles ride that repo's GitHub Releases." \
    --arg channel "$channel" \
    --arg supervisor "$supervisor" \
    --arg core "$core" \
    --arg board "$os_board" \
    --arg os "$os_version" \
    --arg ota "$FAOS_OTA_URL_TEMPLATE" \
    --arg dns "$dns" --arg audio "$audio" --arg cli "$cli" \
    --arg multicast "$multicast" --arg observer "$observer" \
    --arg core_img "$FAOS_CONTAINER_REGISTRY/{machine}-homeassistant" \
    --arg sup_img "$FAOS_CONTAINER_REGISTRY/{arch}-hassio-supervisor" \
    '{
        _comment: $comment,
        channel: $channel,
        supervisor: $supervisor,
        homeassistant: { default: $core },
        hassos: ({ ota: $ota } + { ($board): $os }),
        dns: $dns, audio: $audio, cli: $cli,
        multicast: $multicast, observer: $observer,
        image: { core: $core_img, supervisor: $sup_img }
    }')"

# Validate against the schema when a validator is on PATH (CI installs one).
schema="$ROOT/version-service/schema/channel.schema.json"
if command -v check-jsonschema >/dev/null 2>&1; then
    printf '%s\n' "$doc" | check-jsonschema --schemafile "$schema" - \
        || die "generated document failed schema validation"
elif python3 -c 'import jsonschema' >/dev/null 2>&1; then
    printf '%s' "$doc" | python3 -c '
import json, sys, jsonschema
schema = json.load(open(sys.argv[1]))
jsonschema.validate(json.load(sys.stdin), schema)
' "$schema" || die "generated document failed schema validation"
else
    echo "WARNING: no JSON Schema validator found (check-jsonschema / python3-jsonschema); emitting unvalidated." >&2
fi

if [ -n "$out" ]; then
    printf '%s\n' "$doc" > "$out"
    echo "Wrote $out"
else
    printf '%s\n' "$doc"
fi
